#%RAML 1.0 NamedExample
value:
  -
    moviename: Jalsa
    city: Pune
    theater: City Pride
    date: 2021-10-21
    showtime: 04:30:00
    price: 50.00
    availableseats: 100
  -
    moviename: Arya
    city: Hyderabad
    theater: AMB Cinemas
    date: 2021-09-30
    showtime: 05:30:00
    price: 100.00
    availableseats: 50